### ISSUE TITLE
Can save some gas by using storage keyword

### ISSUE THREAD

**Issue by coffee-converter** [NFT-Worlds/NFT-Worlds-Staking-Rental-Contract#1]
https://github.com/NFT-Worlds/NFT-Worlds-Staking-Rental-Contract/blob/5c06f0ac2d43c5f839ec514da6707a8048bbdce2/src/NFTWEscrow.sol#L171-L179

I noticed this pattern in a few spots... You ought to be able to save users a little bit of gas by using `storage` keyword on line 171 and removing line 179 (instead of `memory` and then writing back to storage).

**Comment by iamarkdev** [comment]
@niftyorca

**Comment by niftyorca** [comment]
`SSTORE` is more expensive than `MSTORE` and `MLOAD`

**Comment by coffee-converter** [comment]
@niftyorca the existing code of course also has to do SSTORE, I assume you meant to say SLOAD in your comment.  The difference is that with SLOAD, you don't need to allocate any extra memory.  Sure, the few field accesses are cheaper via MLOADs, but this ends up being worse overall.

A quick test shows ~6% gas savings for a single token, and ~19% gas savings for 20 tokens.

<img width="751" alt="Screen Shot 2022-02-12 at 2 38 26 AM" src="https://user-images.githubusercontent.com/61335667/153704165-108d0054-ad88-4a2f-86b0-3080ffc7692b.png">

Stripped down testing code (removed a few lines in `updateRent` that are unrelated to the storage var in question):

    //SPDX-License-Identifier: MIT
    pragma solidity 0.8.11;

    contract RentTest {
        struct WorldInfo {
            uint16 weight;          // weight based on rarity
            address owner;          // staked to, otherwise owner == 0
            uint16 deposit;         // unit is ether, paid in WRLD. The deposit is deducted from the last payment(s) since the deposit is non-custodial
            uint16 rentalPerDay;    // unit is ether, paid in WRLD. Total is deposit + rentalPerDay * days
            uint16 minRentDays;     // must rent for at least min rent days, otherwise deposit is forfeited up to this amount
            uint32 rentableUntil;   // timestamp in unix epoch
        }

        WorldInfo[10001] private worldInfo;

        constructor() {
            for (uint i = 1; i <= 20; i++) {
                worldInfo[i] = WorldInfo(
                    1,
                    msg.sender,
                    1,
                    1,
                    1,
                    1
                );
            }
        }
    
        function updateRent(
            uint[] calldata tokenIds,
            uint16 _deposit,
            uint16 _rentalPerDay,
            uint16 _minRentDays,
            uint32 _rentableUntil
        )
            external
        {
            require(uint(_deposit) <= uint(_rentalPerDay) * (uint(_minRentDays) + 1), "ER"); // ER: Rental rate incorrect
            for (uint i = 0; i < tokenIds.length; i++) {
                uint tokenId = tokenIds[i];
                WorldInfo memory worldInfo_ = worldInfo[tokenId];
                require(worldInfo_.weight != 0, "EA"); // EA: Weight not initialized
                require(worldInfo_.owner == msg.sender, "E9"); // E9: Not your world
                worldInfo_.deposit = _deposit;
                worldInfo_.rentalPerDay = _rentalPerDay;
                worldInfo_.minRentDays = _minRentDays;
                worldInfo_.rentableUntil = _rentableUntil;
                worldInfo[tokenId] = worldInfo_;
            }
        }
    
        function updateRentNew(
            uint[] calldata tokenIds,
            uint16 _deposit,
            uint16 _rentalPerDay,
            uint16 _minRentDays,
            uint32 _rentableUntil
        )
            external
        {
            require(uint(_deposit) <= uint(_rentalPerDay) * (uint(_minRentDays) + 1), "ER"); // ER: Rental rate incorrect
            for (uint i = 0; i < tokenIds.length; i++) {
                uint tokenId = tokenIds[i];
                WorldInfo storage worldInfo_ = worldInfo[tokenId];
                require(worldInfo_.weight != 0, "EA"); // EA: Weight not initialized
                require(worldInfo_.owner == msg.sender, "E9"); // E9: Not your world
                worldInfo_.deposit = _deposit;
                worldInfo_.rentalPerDay = _rentalPerDay;
                worldInfo_.minRentDays = _minRentDays;
                worldInfo_.rentableUntil = _rentableUntil;
            }
        }
    }

**Comment by niftyorca** [comment]
> @niftyorca the existing code of course also has to do SSTORE, I assume you meant to say SLOAD in your comment. The difference is that with SLOAD, you don't need to allocate any extra memory. Sure, the few field accesses are cheaper via MLOADs, but this ends up being worse overall.
> 
> A quick test shows ~6% gas savings for a single token, and ~19% gas savings for 20 tokens.
> 
> <img alt="Screen Shot 2022-02-12 at 2 38 26 AM" width="751" src="https://user-images.githubusercontent.com/61335667/153704165-108d0054-ad88-4a2f-86b0-3080ffc7692b.png">
> 
> Stripped down testing code (removed a few lines in `updateRent` that are unrelated to the storage var in question):
> 
> ```
> //SPDX-License-Identifier: MIT
> pragma solidity 0.8.11;
> 
> contract RentTest {
>     struct WorldInfo {
>         uint16 weight;          // weight based on rarity
>         address owner;          // staked to, otherwise owner == 0
>         uint16 deposit;         // unit is ether, paid in WRLD. The deposit is deducted from the last payment(s) since the deposit is non-custodial
>         uint16 rentalPerDay;    // unit is ether, paid in WRLD. Total is deposit + rentalPerDay * days
>         uint16 minRentDays;     // must rent for at least min rent days, otherwise deposit is forfeited up to this amount
>         uint32 rentableUntil;   // timestamp in unix epoch
>     }
> 
>     WorldInfo[10001] private worldInfo;
> 
>     constructor() {
>         for (uint i = 1; i <= 20; i++) {
>             worldInfo[i] = WorldInfo(
>                 1,
>                 msg.sender,
>                 1,
>                 1,
>                 1,
>                 1
>             );
>         }
>     }
> 
>     function updateRent(
>         uint[] calldata tokenIds,
>         uint16 _deposit,
>         uint16 _rentalPerDay,
>         uint16 _minRentDays,
>         uint32 _rentableUntil
>     )
>         external
>     {
>         require(uint(_deposit) <= uint(_rentalPerDay) * (uint(_minRentDays) + 1), "ER"); // ER: Rental rate incorrect
>         for (uint i = 0; i < tokenIds.length; i++) {
>             uint tokenId = tokenIds[i];
>             WorldInfo memory worldInfo_ = worldInfo[tokenId];
>             require(worldInfo_.weight != 0, "EA"); // EA: Weight not initialized
>             require(worldInfo_.owner == msg.sender, "E9"); // E9: Not your world
>             worldInfo_.deposit = _deposit;
>             worldInfo_.rentalPerDay = _rentalPerDay;
>             worldInfo_.minRentDays = _minRentDays;
>             worldInfo_.rentableUntil = _rentableUntil;
>             worldInfo[tokenId] = worldInfo_;
>         }
>     }
> 
>     function updateRentNew(
>         uint[] calldata tokenIds,
>         uint16 _deposit,
>         uint16 _rentalPerDay,
>         uint16 _minRentDays,
>         uint32 _rentableUntil
>     )
>         external
>     {
>         require(uint(_deposit) <= uint(_rentalPerDay) * (uint(_minRentDays) + 1), "ER"); // ER: Rental rate incorrect
>         for (uint i = 0; i < tokenIds.length; i++) {
>             uint tokenId = tokenIds[i];
>             WorldInfo storage worldInfo_ = worldInfo[tokenId];
>             require(worldInfo_.weight != 0, "EA"); // EA: Weight not initialized
>             require(worldInfo_.owner == msg.sender, "E9"); // E9: Not your world
>             worldInfo_.deposit = _deposit;
>             worldInfo_.rentalPerDay = _rentalPerDay;
>             worldInfo_.minRentDays = _minRentDays;
>             worldInfo_.rentableUntil = _rentableUntil;
>         }
>     }
> }
> ```

Very interesting. Sorry I dismissed your original comment too quickly because I saw it as a common pattern in many defi projects.

**Comment by niftyorca** [comment]
We'll just keep the original code. If we apply this pattern also to `_updateRewardsPerWeight` this amounts to very little gas savings, 722065 vs 722144 for staking 50 worlds. I think it's not worth deviating from an audited contract over the gas savings.

The efficiency of these patterns is actually highly dependent on the number of `MLOAD` vs `SLOAD` instructions in that chunk of code. I'll keep that in mind when writing future contracts :)

**Comment by coffee-converter** [comment]
No worries, sounds good!
